[package]
name = "ssh-tunnel"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
db-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
russh = "0.63"
dirs = "6"

[dev-dependencies]
db-postgres.workspace = true
serde_json.workspace = true
tempfile = "3"
